name: Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          echo "Listing project directory..."
          ls -l
          echo "Listing dist directory..."
          ls -l ./dist

      - name: Deploy to server
        if: success()
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          echo "Testing SSH connection..."
          ssh -i private_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "mkdir -p $REMOTE_PATH && echo 'Directory created'"
          echo "Starting rsync..."
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" --delete ./dist/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
